### PR TITLE
Specify cwd in order to work with WSL properly

### PR DESCRIPTION
**Pull request by NoahGorny**
When trying to use this plugin in wsl, I got the following error: `CMD does not support UNC paths as current directories.`
this happened because I was working on files from wsl
This should fix the issue as the cwd will be of sublime

### CODE REVIEW

**Comment by aerobounce** [comment]
I'm not familiar with WSL, let me check some points.

- Using this plugin under Windows Subsystem for Linux — Do you mean something like launch `subl` via WSL then use Pretty Shell?
- Is it not possible to solve it by specifying `shfmt_bin_path`?

**Comment by NoahGorny** [comment]
> I'm not familiar with WSL, let me check some points.
> 
> - Using this plugin under Windows Subsystem for Linux — Do you mean something like launch `subl` via WSL then use Pretty Shell?
> - Is it not possible to solve it by specifying `shfmt_bin_path`?

- The use case I'm referring to is by using regular windows subl to edit files that reside in the the wsl filesystem. When this happens, lunching `Popen` without specifying `cwd` will error our as appearantly UNC filepaths are not supported in CMD
- The problem is not that sublime can not use `shfmt`, it's that CMD fails to lunch. You can get `shfmt` to work by specifying the path to `wsl -e shfmt`

**Comment by aerobounce** [comment]
Okay, understood, sort of... Almost ready to merge.

Last thing, is it fundamental to specify SublimeText executable's path or can it be anything? Seemingly specifying a path in certain system style is crucial but not path itself.
I mean, we already have `sublime` module imported, so if something like `sublime.packages_path()` is okay, we don't have to import `os` module.

**Comment by NoahGorny** [comment]
> Okay, understood, sort of... Almost ready to merge.
> 
> Last thing, is it fundamental to specify SublimeText executable's path or can it be anything? Seemingly specifying a path in certain system style is crucial but not path itself.
> I mean, we already have `sublime` module imported, so if something like `sublime.packages_path()` is okay, we don't have to import `os` module.

I see, I guess I do not know `sublime` plugin development well enough... `sublime_packages_path()` should work. Any path which is not UNC will work
I will change this now :smile:

**Comment by NoahGorny** [comment]
by the way, how do you test your changes? I insert the change into the installed package zip every time and its pretty annoying. Is there a way to test that I just do not know about?

**Comment by aerobounce** [comment]
Cool. Merged!

---

Regarding testing a packages,  in my case, I put working projects in:
`$HOME/Library/Application Support/Sublime Text 3/Packages/`

So Pretty Shell's development dir is:
`$HOME/Library/Application Support/Sublime Text 3/Packages/Pretty Shell`.

Which you can reproduce by `git clone ...` in `Packages` dir.

PATH to `Sublime Text 3/Packages` should be similar in Windows.
You don't have to zip them, raw project folders just work.

**Pull request merged**
